dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - stable
env:
  - CODECLIMATE_REPO_TOKEN=760f0ece2309fe413a1f3018f6c7ed17f5ddaefaf661670b795f507e91731eb4
  - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage CODECLIMATE_REPO_TOKEN=d5162c9e-5040-4bf1-a756-77612acfdb1f
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn config set registry "https://registry.npmjs.org"
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codeclimate-test-reporter
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
